server:
  port: 19098
spring:
  application:
    name: auth-service
  config:
    import: optional:file:.env[.properties]

jwt:
  secret: ${JWT_SECRET_KEY}
  access-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

eureka:
  client:
    service-Url:
      defaultZone: http://localhost:19090/eureka/

