spring:
  application:
    name: benefit-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 50
    open-in-view: false
  jackson:
    serialization:
      fail-on-empty-beans: false
  data:
    redis:
      host: redis-master
      port: 6379
      username: default
      password: systempass
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: >
          point-issued:com.waitless.common.event.PointIssuedEvent,
          point-issued-failed:com.waitless.common.event.PointIssuedFailedEvent
    consumer:
      group-id: point-service
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.waitless.common.event
        spring.json.type.mapping: >
          review-created:com.waitless.common.event.ReviewCreatedEvent,
          review-deleted:com.waitless.common.event.ReviewDeletedEvent
    listener:
      ack-mode: MANUAL_IMMEDIATE
app:
  kafka:
    topics:
      review-created-events: review-created-events
      review-deleted-events: review-deleted-events
      point-issued-events: point-issued-events
      point-issued-failed-events: point-issued-failed-events

#point:
#  max-bonus: 1000
#  daily-attendance-point: 100
#  reward-point-on-review: 100
#  cache-ttl-seconds: 300

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:19090/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 120

server:
  port: 19096

logging:
  level:
    root: info
    com.waitless.benefit.point: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
