### 회원가입
POST http://localhost:19091/api/users/signup
Content-Type: application/json

{
  "email": "user3@gmail.com",
  "password": "user3",
  "name": "user3",
  "phone": "010-1234-1236",
  "role" : "ADMIN",
  "slackId": "user3@gmail.com"
}

### 유저 검증
POST http://localhost:19092/api/users/app/validate
Content-Type: application/json

{
  "email": "user1@gmail.com",
  "password": "user1"
}

### 유저 단건 조회
GET http://localhost:19091/api/users/1