spring:
  application:
    name: server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:19090/eureka/
    fetch-registry: false
    register-with-eureka: false
server:
  port: 19090