spring:
  application:
    name: server
eureka:
  instance:
    hostname: eureka-server
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://eureka-server:19090/eureka
    fetch-registry: false
    register-with-eureka: false
server:
  port: 19090