server:
  port: 19091
spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        # 유저
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**, /user-service/**
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        # auth
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**, /auth-service/**
          filters:
            - RewritePath=/auth-service/(?<segment>.*), /$\{segment}
        # 식당
        - id: restaurant-service
          uri: lb://restaurant-service
          predicates:
            - Path=/api/restaurants/**, /api/categories/** , /api/menus/**, /restaurant-service/**
          filters:
            - RewritePath=/restaurant-service/(?<segment>.*), /$\{segment}
        # 예약
        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/api/reservations/**, /reservation-service/**
          filters:
            - RewritePath=/reservation-service/(?<segment>.*), /$\{segment}
        # 리뷰
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/api/reviews/**, /review-service/**
          filters:
            - RewritePath=/review-service/(?<segment>.*), /$\{segment}
        # 혜택
        - id: benefit-service
          uri: lb://benefit-service
          predicates:
            - Path=/api/points/**, /api/coupons/**, /benefit-service/**
          filters:
            - RewritePath=/benefit-service/(?<segment>.*), /$\{segment}
        # 메시지
        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/api/slacks/**, /message-service/**
          filters:
            - RewritePath=/message-service/(?<segment>.*), /$\{segment}
      globalcors:
        corsConfigurations:
          "[**]":
            allowedOriginPatterns:
              - "http://localhost:19091"  # 게이트웨이
              - "http://localhost:19092"  # 유저
              - "http://localhost:19098"  # auth
              - "http://localhost:19093"  # 식당
              - "http://localhost:19094"  # 예약
              - "http://localhost:19095"  # 리뷰
              - "http://localhost:19096"  # 혜택
              - "http://localhost:19097"  # 메시지
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
            allowedHeaders:
              - "*"
            allowCredentials: true

      discovery:
        locator:
          enabled: true
  config:
    import: optional:file:.env[.properties]

eureka:
  client:
    service-Url:
      defaultZone: http://localhost:19090/eureka/

jwt:
  secret: ${JWT_SECRET_KEY}
