spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mariadb://localhost:3306/hangry-database
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 50
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379
      password: systempass

eureka:
  client:
    service-Url:
      defaultZone: http://localhost:19090/eureka/
server:
  port: 19099