server:
  port: 19092
spring:
  application:
    name: user-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
  config:
    import: optional:file:.env[.properties]

logging:
  level:
    root: info
    com.waitless.user: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

eureka:
  client:
    service-Url:
      defaultZone: http://localhost:19090/eureka/

