spring:
  application:
    name: reservation-service

  datasource:
    url: jdbc:mariadb://localhost:3306/reservation
    username: root # 임시
    password: 1234 # 임시
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass

logging:
  level:
    root: info
    com.waitless.reservation: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

server:
  port: 19099 # 임시