spring:
  application:
    name: reservation-service

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: >
          stock-decrease:com.waitless.common.event.StockDecreasedEvent
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.waitless
        spring.json.type.mapping: >
          stock-decrease:com.waitless.common.event.StockDecreasedEvent

  datasource:
    url: jdbc:mariadb://localhost:3306/hangry-database?allowPublicKeyRetrieval=true&useSSL=false
    username: root # 임시
    password: root # 임시
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass

  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 3000
            read-timeout: 5000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    root: info
    com.waitless.reservation: info
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql: info

server:
  port: 19094

gateway:
  url: http://localhost:19091

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always