server:
  port: 19093

spring:
  application:
    name: restaurant-service
  datasource:
    url: jdbc:mariadb://localhost:3307/hangry-database
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/