name: Deploy

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      JWT_ACCESS_EXPIRATION: ${{ secrets.JWT_ACCESS_EXPIRATION }}
      JWT_REFRESH_EXPIRATION: ${{ secrets.JWT_REFRESH_EXPIRATION }}
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Java 설치
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: DockerHub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Gradle 실행 권한 부여
        run: chmod +x ./gradlew

      - name: Spring Build
        run: ./gradlew clean bootJar -x test

      - name: 빌드 파일명 통일
        run: |
          SERVICES="auth-service user-service reservation-service restaurant-service review-service benefit-service message-service gateway"
          for SERVICE in $SERVICES
          do
            mv $SERVICE/build/libs/*-SNAPSHOT.jar $SERVICE/build/libs/app.jar
          done

      - name: Tag 생성
        id: vars
        run: echo "tag=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Docker 이미지 Build, Push
        run: |
          PROJECTS="auth-service user-service reservation-service restaurant-service review-service benefit-service message-service gateway server"
          for PROJECT in $PROJECTS
          do
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${PROJECT}:${{ env.tag }} -f ${PROJECT}/Dockerfile ${PROJECT}
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/${PROJECT}:${{ env.tag }}
          done

      - name: Kubeconfig Setup
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > $HOME/.kube/config

      - name: Kubernetes에 배포
        run: |
          declare -A SERVICE_MAP=(
            ["auth-service"]="auth-service"
            ["user-service"]="user-service"
            ["reservation-service"]="reservation-service"
            ["restaurant-service"]="restaurant-service"
            ["review-service"]="review-service"
            ["benefit-service"]="benefit-service"
            ["message-service"]="message-service"
            ["gateway"]="gateway-service"
            ["server"]="eureka-server"
          )
          
          for PROJECT in "${!SERVICE_MAP[@]}"
          do
            SERVICE_NAME=${SERVICE_MAP[$PROJECT]}
            kubectl set image deployment/${SERVICE_NAME} ${SERVICE_NAME}-container=${{ secrets.DOCKERHUB_USERNAME }}/${PROJECT}:${{ env.tag }}
          done